"""fix_refresh_tokens_id_column

Revision ID: 2d0225a0f713
Revises: efabc059c2a1
Create Date: 2025-08-19 12:57:12.027634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0225a0f713'
down_revision = 'efabc059c2a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
