"""fix_todo_model_constraints_and_optional_duedate

Revision ID: 6b7b656701ab
Revises: 31cf81c20aae
Create Date: 2025-08-19 17:58:49.066234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b7b656701ab'
down_revision = '31cf81c20aae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'dueDate',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint('todos_title_key', 'todos', type_='unique')
    op.create_unique_constraint('unique_title_per_user', 'todos', ['title', 'userId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_title_per_user', 'todos', type_='unique')
    op.create_unique_constraint('todos_title_key', 'todos', ['title'])
    op.alter_column('todos', 'dueDate',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
