"""fix_refresh_tokens_id_default

Revision ID: a07006aadb2a
Revises: 2d0225a0f713
Create Date: 2025-08-19 12:59:30.497136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07006aadb2a'
down_revision = '2d0225a0f713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
