"""Add default values to description and category

Revision ID: efabc059c2a1
Revises: f44707f530cc
Create Date: 2025-08-19 11:36:20.869052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efabc059c2a1'
down_revision = 'f44707f530cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('todos', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('todos', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
